activate: ''
config: ''
datasource: ''
ddl-auto: none
dialect: org.hibernate.dialect.PostgreSQL10Dialect
driverClassName: org.h2.Driver
format_sql: true
hibernate: ''
init: ''
jpa: ''
jpa.JpaTransactionManager: DEBUG
level: ''
logging: ''
mode: always
on-profile: ci,test
org: ''
orm: ''
password: test
properties: ''
spring: ''
springframework: ''
sql: ''
transaction: INFO
transaction.interceptor: TRACE
url: jdbc:h2:mem:shareit
username: test
