DROP TABLE IF EXISTS users, requests, items, bookings, comments cascade;

CREATE TABLE IF NOT EXISTS users (
  id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name  VARCHAR(255)                            NOT NULL,
  email VARCHAR(512)                            NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description  text                                    NOT NULL,
  created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  requester_id BIGINT REFERENCES users (id) ON delete CASCADE,
  CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name        VARCHAR(255)                            NOT NULL,
  description text                                    NOT NULL,
  available   BOOLEAN                                 NOT NULL,
  owner_id    BIGINT                                  NOT NULL REFERENCES users (id) ON delete CASCADE,
  request_id  BIGINT REFERENCES requests (id) ON delete CASCADE,
  CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  end_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  item_id    BIGINT                                  NOT NULL REFERENCES items (id) ON delete CASCADE,
  user_id    BIGINT                                  NOT NULL REFERENCES users (id) ON delete CASCADE,
  status VARCHAR(50),
  CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text    text                                    NOT NULL,
  item_id BIGINT                                  NOT NULL REFERENCES items (id) ON delete CASCADE,
  user_id BIGINT                                  NOT NULL REFERENCES users (id) ON delete CASCADE,
  created TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  CONSTRAINT pk_comment PRIMARY KEY (id)
);

